# Generated by Django 2.2 on 2019-04-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('categories', models.CharField(max_length=300)),
                ('comment_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('icon', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('comment_date', models.DateTimeField()),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.User')),
            ],
        ),
    ]
