# Generated by Django 2.2 on 2019-04-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(null='true', verbose_name='posted Date'),
            preserve_default='true',
        ),
    ]
