# Generated by Django 2.2 on 2019-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_posts_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(null='true'),
        ),
    ]
